### ISSUE TITLE
license

### ISSUE THREAD

**Issue by jwijffels** [allenai/genia-dependency-trees#1]
Thanks for distributing these conllu files. 
Is there also a license alongside this and a way to cite this?

**Comment by DeNeutoy** [comment]
Hi @jwijffels,

I just added the original GENIA license. For the pubmed content you should check the policy here: https://www.ncbi.nlm.nih.gov/home/about/policies/

Let me know if you need more info than that.

**Comment by jwijffels** [comment]
Thanks for including the license.
Maybe adding this pubmed content link to another LICENSE file would be suited.

Question. Does this license impact somehow the distribution or usage of the models provided at https://allenai.github.io/scispacy

**Comment by DeNeutoy** [comment]
The original license includes this detail.

Scispacy's usage of the corpus is compatible with the terms of the license.

**Comment by jwijffels** [comment]
Thank you for the short clarification. Can I conclude from https://github.com/allenai/genia-dependency-trees/blob/master/GENIA_LICENSE#L14 that using scispacy is basically at your own risk?

**Comment by DeNeutoy** [comment]
Scispacy's models are Apache 2.0 licensed. If you require further clarification on how the license applies to the genia corpus, you would need to consult a lawyer, unfortunately. Sorry I can't give clearer advice!
