### ISSUE TITLE
tokenizer used

### ISSUE THREAD

**Issue by jwijffels** [allenai/genia-dependency-trees#2]
I'm thinking about building an UDPipe model for doing pos tagging and dependency parsing to compare it to the models provided at https://allenai.github.io/scispacy
If I look at the GENIA treebank raw data e.g. https://github.com/allenai/genia-dependency-trees/blob/master/original_data/GENIA_treebank_v1/10023774.xml
I don't see any spaces or punctuation symbols in there. Hence my question. 
- How is that tokenisation done? 
- Where are the raw untokenised sentences ?

**Comment by DeNeutoy** [comment]
Hi @jwijffels ,

I do not know how the GENIA treebank was originally tokenized. I suggest you look at the paper, but it is likely using the GENIA tokenizer.

The raw untokenised sentences are here: https://github.com/allenai/genia-dependency-trees/tree/master/raw/dev

**Comment by jwijffels** [comment]
Thanks for the information.
